# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a145420996a510026da54d8f73e11f73c53a61376bd1f4fc71d26149e484a072f237dd9f49a31e728e4203bdc87495f82e00b9c12d8bd9fce866e34ccc50e63

test:
  secret_key_base: 2bb1531d02ae1237329f03237e26bf967fb748889f560bb7e1d3a541194b8c06faebf254d07ab312b483860be679806917655f64600e9c7e514e00b666fb173b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
